name: Add a release note (WIP)
description: Add a new Ubuntu release note
labels:
  - 'New release note'
assignees:
  - msuchane
body:
- type: dropdown
  attributes:
    label: Ubuntu release
    description: Which Ubuntu release is affected by this change?
    options:
      - '25.10'
      - '26.04 LTS'
      - '26.10'
      - '27.04'
      - '27.10'
      - 'Other (specify in the description)'
    default: '26.04 LTS'
  validations:
    required: true
